### ISSUE TITLE
Keyword metadata sometimes doesn't get mapped to VLO facet

### ISSUE THREAD

**Issue by jakoble** [clarin-eric/metadata-curation#11]
See here: https://vlo.clarin.eu/search?18&q=Multilingual+comparable+corpora+of+parliamentary+debates+ParlaMint+4.1

All three corpora listed above have keywords specified in the metadata, but they don't show up as a VLO facet.

By contrast, this is not an issue with this corpus: https://vlo.clarin.eu/record/http_58__47__47_hdl.handle.net_47_11500_47_CLARIN-EL-0000-0000-7603-8_64_format_61_cmdi?23&q=Multilingual+comparable+corpora+of+parliamentary+debates+ParlaMint+3.0&index=1&count=7

I presume this has something to do with the difference in repositories (the CLARIN.SI one vs. the CLARIN:EL inventory) and how the metadata are represented there.

**Comment by twagoo** [comment]
For reference:
* [Record report for "Multilingual comparable corpora of parliamentary debates ParlaMint 4.1"](https://curation.clarin.eu/curate?url-input=https%3A%2F%2Fhdl.handle.net%2F11356%2F1912%40format%3Dcmdi)
* [Record report for "Linguistically annotated multilingual comparable corpora of parliamentary debates ParlaMint.ana 4.1"](https://curation.clarin.eu/curate?url-input=https%3A%2F%2Fhdl.handle.net%2F11356%2F1911%40format%3Dcmdi)
* [Record report for "Linguistically annotated multilingual comparable corpora of parliamentary debates in English ParlaMint-en.ana 4.1"](https://curation.clarin.eu/curate?url-input=https%3A%2F%2Fhdl.handle.net%2F11356%2F1910%40format%3Dcmdi)

According to the reports, the profile [clarin.eu:cr1:p_1403526079380](https://catalog.clarin.eu/ds/ComponentRegistry?item=clarin.eu:cr1:p_1403526079380) does not map to the keywords field, however the concept http://hdl.handle.net/11459/CCR_C-278_336dd81a-626b-713e-c74a-34fa2ca26a71 is specified for that field in [facetConcepts.xml](https://github.com/clarin-eric/VLO-mapping/blob/master/mapping/facetConcepts.xml). Needs some closer looking into..

**Comment by twagoo** [comment]
I expect that once the fix in https://github.com/clarin-eric/VLO-mapping/pull/51 has been applied (i.e. on next import which will be tonight) this situation should automatically improve. To be confirmed :)
