### ISSUE TITLE
Broken OAI provider for CELR-EKK

### ISSUE THREAD

**Issue by kreetrapper** [clarin-eric/metadata-curation#7]
OAI [provider](https://metashare.ut.ee/oai_pmh/) for CELR-EKK is broken.

Their website is running and the OAI provider had recently been fixed.

**Comment by kreetrapper** [comment]
Wrote a mail to Krista to ask about this.

**Comment by dietervu** [comment]
OAI endpoint seems to be fixed: https://metashare.ut.ee/oai_pmh/?verb=Identify
