### ISSUE TITLE
Website for C Centre Cedifor is broken

### ISSUE THREAD

**Issue by kreetrapper** [clarin-eric/metadata-curation#9]
The website for [Cedifor](https://centres.clarin.eu/centre/35) is currently broken.

**Comment by kreetrapper** [comment]
We have successfully contacted them and they are planning to have the website back up soon (probably this week).

**Comment by dietervu** [comment]
Also the [SSL certificate for the contact URLs in the centre registry](https://hucompute.org/team/giuseppe-abrami) is no longer valid: 

> Web sites prove their identity via certificates, which are valid for a set time period. The certificate for hucompute.org expired on 28/11/2023.

**Comment by kreetrapper** [comment]
The general centre website is available again and the website for the contacts have been updated.
